### ISSUE TITLE
Download and scale speaker images on fetch

### ISSUE THREAD

**Issue by knuthaug** [javaBin/javazone-video#12]
We need to download the speaker images and scale them locally. Incogito has all kinds of sizes. 
Plan:
- download and save under filename speaker.slug.{png|jpg}
- Scale to e.g. short edge=200 (whatever fits)
- commit to repo?
- serve locally on speaker page
  @huboard:{"order":16.5}

**Comment by bjartek** [comment]
IMHO this is a problem that should be solved in incogito. We should be able to link directly to the images that we get from the server. 

What about for now just linking to the images and force the size down in the img tag? not optimal but it works.

**Comment by knuthaug** [comment]
Good point. Is fixing this in incogito a quick thing? I think we need several sizes then, or perhaps something to scale on demand (?)

I thought about what we should do with speakers without uploaded images, and perhaps being able to store an image locally for them and checking for no (or null) images in the incogito json. 

I already wrote some code for it, but it isn't all that much. And we can use it before incogito gets a fix.

**Comment by knuthaug** [comment]
Another benefit from doing this in incogito is that the web page can select a fitting size instead of using whatever the speaker uploaded and scale in-browser.

**Comment by bjartek** [comment]
Even though I think it is the best sollution to let incogito do it I am not sure it will be done in the near future unfortunately. AFAIK incogito does not do anything with the picture except storing them. 

So if we already have the code we should just go for it.
