### ISSUE TITLE
Include comments and plays from vimeo in video-page and frontpage

### ISSUE THREAD

**Issue by knuthaug** [javaBin/javazone-video#13]
We need the plays, likes and comments from vimeo in the talk object, so we can display it on the video
page and the frontpage listing of a video. 

This data also needs to be periodically updated (see http://www.playframework.org/documentation/1.2/jobs)

**Comment by bjartek** [comment]
Does the background job have to merge all information from vimeo back into the local domain object? What if the title or tags for a video change?

**Comment by knuthaug** [comment]
I would say it needs to refresh _some_ data. Embed code, for instance likely won't change, same with the thumbnails. Titles can change, but rarely. Plays, likes and comments will change often. Tags can change periodically, but rather seldom.  

But some logic around checking if content for a given field has changed and updating it will be necessary, probably.

But I guess updating Incogito info is of lesser importance, as it is not very likely to change after a conference instance.

**Comment by knuthaug** [comment]
And if the title changes, it can be interesting since the initial merge is done via title matching now. But if we store the vimeo id (which we do) and the incogito uuid (which we don't store at present), we could match on that after the initial merge.

**Comment by bjartek** [comment]
Part one of this job is now done. The automatic job remains.

**Comment by knuthaug** [comment]
Should we perhaps also have some way of showing the actual comments on the site? Use http://vimeo.com/api/docs/methods/vimeo.videos.comments.getList to fetch a list and show it? If so we could perhaps periodically refresh it, like with plays, likes etc.

**Comment by bjartek** [comment]
It is a nice to have in my eyes. So schedule it for the next version?

**Comment by knuthaug** [comment]
Unsure on the use of the comments, as they are few and far between. Even the most viewed video, with 6700+ views, have a whopping 11 comments, mostly "thanks" and "great talk"
