### ISSUE TITLE
Better tagging

### ISSUE THREAD

**Issue by knuthaug** [javaBin/javazone-video#21]
This is not something we fix on the site per se, but I feel the tagging of the videos is a bit lacking. Most videos are tagged with
javaZone JavaBin Conference Java JavaZone 2011 even if the talk is on scala (for instance). Some have a tag for the speaker name, some haven't.
1. I feel there is a bit redundancy in the default tags. Maybe we should filter a bit? Remove Conference (filter on site, not remove in vimeo). Filter javazone $year (we know it's javazone, or else it wouldn't be on the site. 
2. It needs more detailed tags (language, tool, framework etc). 

@huboard:{"order":35.0}

**Comment by bjartek** [comment]
I agree very much on this one. I can hear on the landskongress if we can do some work on tagging the video's better. Perhaps even do it there!
