### ISSUE TITLE
Add twitter account for speaker

### ISSUE THREAD

**Issue by knuthaug** [javaBin/javazone-video#23]
We should perhaps link to the twitter account for a speaker. We could do this by (manually) creating a mapping file by collecting twitter handles in text/yml-file and looking up during initial read. 

Bonus for later version: show n last tweets from speaker on video page or speaker page?

**Comment by bjartek** [comment]
It would also be nice to see tweets that are related to this video. Let's say a tweek that contains some predefined tags?

**Comment by knuthaug** [comment]
Yes! Thought of that but forgot to mention. Can be tricky to get quality into the tweets, but worth a try. But I guess this then will depend on #21 (better tagging) too.

**Comment by bjartek** [comment]
what if we just add a tag to the videos on vimeo that starts with @ and say that it is the twitter handle? we can also add tags that start with # to indicate twitter hashtags?

So f.eks for my lighting talk this year I can add tags @bjartek #iosVSandroid and based on that we should be able to fetch twitter stuff? 

Would also be cool to ask speakers for next year to supply twitter handle and hashtag used for tracking tweets related to this talk!

**Comment by knuthaug** [comment]
I have started a mappings file (conf/mappings.yml) which does a mapping between the speaker slug name and the twitter handle. But it also does mapping to other vimeo videos for the speaker (see Kevlin Henney for an example). I think this is a cool feature too, and we can't solve that in the tags, I think. This mapping file could also map to other stuf (like blog/homepage) for an speaker. 

Would wish to do this dynamically, but the searchability of the viedoes is somewhat varying since tagging/titles varies a lot.

The talk hashtag(s) is perhaps better suited for including in the tags. 

+1 on the idea to ask that of speakers in incogito next year!
