### ISSUE TITLE
Size of thumbnails

### ISSUE THREAD

**Issue by bjartek** [javaBin/javazone-video#27]
The sizes of the thumbnails varies and it looks like the reported thumbnail size is not always right. Look at the image of the most popular video. 
http://b.vimeocdn.com/ts/193/051/193051583_640.jpg

It is 640 x 320 but is shown with a hight of 204 thus it is stretched. 

Why are we not just showing the link to vimeo on the frontpage. Does it generate that much load?

**Comment by bjartek** [comment]
tried out showing the vimeo link on the frontpage and it does not work. generates way to much load.

**Comment by knuthaug** [comment]
You tried the actual video player on the front page? 

We just link to the vimeo cdn thumbnail on the front page, with the height and width set in the database. Perhaps a bug in the vimeo-client class (or jsonMapper for vimeo) that is a bit sloppy with the sizes/ratio on the thumbnail image. That is my suspsicion. I'll create the bug

**Comment by knuthaug** [comment]
Very strange. For this image, the sizes in the json from vimeo is 640x204, but the actual size is different. To fix this we either need vimeo to fix it (can't hurt to report a bug on it) or for specific (or all) images, read it into a bufferedImage and read the width and height. That will slow down the storing of the videos considerably.

**Comment by knuthaug** [comment]
Generated new preview images on vimeo for some of the most glaring mistakes.
